import { McApiPacketType } from "../../Data/Enums";
import { Vector2 } from "../../Data/Vector2";
import { Vector3 } from "../../Data/Vector3";
import { NetDataReader } from "../NetDataReader";
import { NetDataWriter } from "../NetDataWriter";
import { McApiPacket } from "./McApiPacket";
export declare class McApiEntityCreatedPacket extends McApiPacket {
    constructor(id?: number, loudness?: number, lastSpoke?: bigint, worldId?: string, name?: string, muted?: boolean, deafened?: boolean, talkBitmask?: number, listenBitmask?: number, effectBitmask?: number, position?: Vector3, rotation?: Vector2, caveFactor?: number, muffleFactor?: number);
    get PacketType(): McApiPacketType;
    get Id(): number;
    get Loudness(): number;
    get LastSpoke(): bigint;
    get WorldId(): string;
    get Name(): string;
    get Muted(): boolean;
    get Deafened(): boolean;
    get TalkBitmask(): number;
    get ListenBitmask(): number;
    get EffectBitmask(): number;
    get Position(): Vector3;
    get Rotation(): Vector2;
    get CaveFactor(): number;
    get MuffleFactor(): number;
    private _id;
    private _loudness;
    private _lastSpoke;
    private _worldId;
    private _name;
    private _muted;
    private _deafened;
    private _talkBitmask;
    private _listenBitmask;
    private _effectBitmask;
    private _position;
    private _rotation;
    private _caveFactor;
    private _muffleFactor;
    Serialize(writer: NetDataWriter): void;
    Deserialize(reader: NetDataReader): void;
}
